apiVersion: v1
kind: Service
metadata:
  name: rapidfort_project_service
  labels:
    app: 20103063_rapidfort_project
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: 20103063_rapidfort_project
